apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}ui-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 2 # replicaset
  selector:
    matchLabels:
      app: meetupui # there will always be two pods running matching this label
  template: #pod template
    metadata:
      labels:
        app: meetupui # pod label
    spec:
      containers:
        - name: meetupui
          image: {{ .Values.meetupui.container.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              port: 80
              path: /status.html
            initialDelaySeconds: 3 #Default 0
            periodSeconds: 5 #Default 10
            failureThreshold: 3 #Default 3
          livenessProbe:
            httpGet:
              port: 80
              path: /status.html
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef: #config map can be attached as volumes too just that env variables are easy to access
                name: {{ .Release.Name }}ui-configmap