apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}api-service
spec:
  type: ClusterIP
  selector:
    app: meetupapiservice
  ports:
    - port: 80 #ClusterIP Port
      targetPort: 80
      name: http-api